In [26]:
import numpy as np # import file
from numpy import random as rd

In [27]:
a=np.array([[1,2,3,4,5,6],[1,2,344,5,6,7]]) #create array

array([[  1,   2,   3,   4,   5,   6],
       [  1,   2, 344,   5,   6,   7]])

In [30]:
b=np.array([1,2,3,4,5,6]) # create 1-d array
np.array([1,2,3],dtype="complex") # create complex array
np.array((1,2,3)) # create tuple array

array([1, 2, 3, 4, 5, 6])

In [4]:
np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(10,20,2) # array([10, 12, 14, 16, 18])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.zeros([0]*10) # array([], shape=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0), dtype=float64)

array([], shape=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0), dtype=float64)

In [7]:
np.zeros([3,4])
np.ones([2,2],dtype='int')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.linspace(1,100,num=5) #array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]) equal divide

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [34]:
rd.rand(3) # uniform distribution array([0.35998483, 0.76821598, 0.52841454])
rd.random([2,5]) # positive or negative standard value

array([0.35998483, 0.76821598, 0.52841454])

In [13]:
rd.randint(5,size=(2,2)) # random int value range of 5

array([[0, 3],
       [2, 4]])

In [36]:
b.ndim # op 1 dim
b.shape# (6,)
b.size# 6 column
b.dtype

dtype('int32')