In [34]:
import numpy as np

In [35]:
a=np.arange(10) #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b=np.random.random([2,2])
c=np.random.random([2,2,2])


In [36]:
a[6] # 6
b[0][0] # 0.07332029364267156
c[0][0][0] # 0.6757686343370001

0.13714094420042178

In [21]:
# 1-d array
a[:] #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[1:] # array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[:-1] # array([0, 1, 2, 3, 4, 5, 6, 7, 8])
a[1:3] # array([1, 2])
a[1::2] # array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [22]:
# 2-d array
b[1:,1:] # array([[0.78539928]])
b[:,:] # print all
b[::,::] # print all but we add step also 
c[:,:,:] # print all

array([[0.78539928]])

In [24]:
# Advanced Indexing
x=np.array([1,2,3,4,5,6])
b=np.array([1,3,5])
a[b] # array([1, 3, 5]) like passing index values in a array

array([1, 3, 5])

In [30]:
a=np.arange(10)
a+1 # array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a-1 # array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])
a*2 # array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
a**2 # array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)
a%2 # array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [31]:
# if the shape of array will be same then we add directly
# if shape not same then we use broadcasting technique


In [55]:
b.ravel() #Flatten the array
b.reshape(2,-2) # reshape
b.resize((4,1)) # resize
np.append(a,b) # Append items to an array
np.insert(a, 1, 5)
np.delete(a,[1])
c=np.arange(5)
np.concatenate((a,c),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4])